#!/usr/bin/env bash
#  0. World wide web 
get_a_record() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for subd in "${subdomains[@]}"; do
        dig_result=$(dig +short A "$subd"."$domain")
        echo "$subd $dig_result"| awk '{print "The subdomain " $1 " is an A record and points to " $2}'
            # echo "The subdomain $subd is an A record and points to $dig_result"
    done
}

get_a_record "$1" "$2"
