#!/usr/bin/env bash
#  0. World wide web 
get_a_record() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for subd in "${subdomains[@]}"; do
        dig "$subd"."$domain" | awk '/;; ANSWER SECTION:/ {getline; print "The subdomain '"$subd"' is a " $4 " record and points to " $5}'
    done
}

get_a_record "$1" "$2"
