#!/usr/bin/env bash
#  1. Install nginx web server 
sudo apt-get update
sudo apt-get -y install nginx 
sudo chmod -R 755 /var/www
sudo chown -R $USER:$USER /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo systemctl restart nginx