#!/usr/bin/env bash
#  1. Install nginx web server 
apt-get update
apt-get -y install nginx 
touch /var/www/html/index.html
echo "Hello, world!" > /var/www/html/index.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}" > /etc/nginx/sites-available/default
systemctl restart nigix