#!/usr/bin/env bash
#  1. Install nginx web server 
sudo apt-get update
sudo apt-get -y install nginx 
sudo chmod -R 755 /var/www
sudo chown -R $USER:$USER /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
        location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
