#!/usr/bin/env bash
#  4. Not found page 404 

sudo apt-get update
sudo apt-get -y install nginx 

sudo chmod -R 755 /var/www
sudo chown -R $USER:$USER /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html


sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo sed -i "s/#error_page 404/error_page 404/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo service nginx restart
