#!/usr/bin/env bash
# 0. Double the number of webservers 
sudo apt update
sudo apt install -y nginx


sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html


hostname_short=$(hostname -s)
scho "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://thedreamcatcher.dev permanent;
	}
	error_page 404 /404.html;
	
    
    location = /404.html {
		internal;
	}
}
" | sudo tee /etc/nginx/sites-available/default



sudo sed -i "/server_name _;/a add_header X-Served-By $hostname_short;" /etc/nginx/sites-available/default
sudo service nginx restart
