#!/usr/bin/env bash
# 0. Double the number of webservers 

hostname_short=$(hostname -s)
sudo sed -i "/server_name _;/a add_header X-Served-By $hostname_short;" /etc/nginx/sites-available/default
sudo service nginx restart
