#!/usr/bin/env bash
#  1. Install your load balancer

sudo apt update
sudo apt-get install -y haproxy

sudo cp /etc/default/haproxy /etc/default/haproxy.orig

echo '
ENABLED=1
' | sudo tee -a /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

echo '
frontend web-front
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 530990-web-01 34.201.165.130:80 check
        server 530990-web-02 34.224.62.173:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
