#!/usr/bin/env bash
# echo Best schol 10 times
v=1;
while [ $v -ne 101 ];
do
    if  (( $v % 5 == 0 && $v % 3 == 0 ));
    then echo "FizzBuzz"
    elif  ((  $v % 3 == 0 ));
    then echo "Fizz"
    elif  (( $v % 5 == 0 ));
    then echo "Buzz"
    else
        echo $v;

    fi;
    ((v++));
done;