#!/usr/bin/env bash
# edit hosts file

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new

if grep -q "facebook.com" ./hosts.new; then
   sed -i s/31.13.66.35/8.8.8.8/ ~/hosts.new

else
    echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
