#!/usr/bin/env bash
# kill gracefulyy gunicorn and start again
GUNICORN_PID=$(pgrep gunicorn)

if [ -z "$GUNICORN_PID" ]; then
    echo "Gunicorn is not running!"
    exit 1
fi

echo "Gracefully reloading Gunicorn..."

# Send the HUP signal to the master process to reload configuration and code
kill -HUP $GUNICORN_PID

# Wait for a few seconds to give Gunicorn time to reload
sleep 5

# Check if Gunicorn is still running
NEW_GUNICORN_PID=$(pgrep gunicorn)

if [ -z "$NEW_GUNICORN_PID" ]; then
    echo "Failed to reload Gunicorn!"
    exit 1
else
    echo "Gunicorn reloaded successfully!"
    exit 0
fi
